### PR TITLE
Card devexp_416 - Clean and update wildfly image to follow recent changes in STI

### PR DESCRIPTION
**Pull request by soltysh**
This as long as other image updates (https://github.com/openshift/nodejs-0-10-centos/pull/3,
https://github.com/openshift/ruby-20-centos/pull/7) should be merged only after openshift/source-to-image#98 is merged and origin is updated with latest STI version.

### CODE REVIEW

**Comment by soltysh** [comment]
Addressed @mfojtik's [comment](https://github.com/openshift/ruby-20-centos/pull/7#discussion_r22587383).

**Comment by mfojtik** [comment]
LGTM

**Comment by bparees** [comment]
same comment here as in the ruby-20-centos PR regarding testing.

**Comment by soltysh** [comment]
https://github.com/openshift/ruby-20-centos/pull/7#issuecomment-69719884

**Comment by mfojtik** [comment]
tests are running.... feel free to merge this once the tests are green

**Pull request merged**
