### PR TITLE
Updated database configuration

### PR DESCRIPTION
**Pull request by sebplorenz**
I made some changes that help to work with databases (and I hope that these changes may help others):

1. Changed env variable for db host and port to the ones without the included port number, e.g. $MYSQL_PORT_3306_TCP_PORT to $MYSQL_SERVICE_PORT.
2. Added env variable $POSTGRESQL_DATASOURCE and $MYSQL_DATASOURCE to easily set the name of the datasource from outside.
4. If either a Postgre- or MySQL DS is available then this DS is taken as the default datasource (Before this the configuration always used the H2 ExampleDS as the default DS.)
3. Set the name of the default datasource from outside, so that you can still use the ExampleDS even if a Postgre- or MySQL DS is set.

All changes are backwards compatible and will not effect current setups.

### CODE REVIEW

**Comment by sebplorenz** [comment]
Btw. I'm using the openshift-origin docker container to run OpenShift locally. When I try to run the test script then it complains that 'sti' is an unknown command. How can I install it (preferably without building the sti repository)?

**Comment by bparees** [comment]
you could download an sti release:
https://github.com/openshift/source-to-image/releases/tag/v1.0
and install the binary that way.

**Comment by bparees** [comment]
changes look good but can you squash your commits?

thanks!

**Comment by soltysh** [comment]
@bparees are you ok with merging this now?

**Comment by bparees** [comment]
@soltysh no, there's still a merge commit that doesn't belong from what i'm seeing.

**Comment by soltysh** [comment]
@bparees that commit you're talking about was part of #42 PR, which was already merged. So in the end this PR will just add the database changes.

**Comment by bparees** [comment]
@soltysh that commit is the same changes as the other PR but it has a new commit id here, we should not merge it as is.  (I confirmed with @danmcp )

**Comment by bparees** [comment]
@sebplorenz can you clean this up so it just has your new commit?

Thanks

**Comment by soltysh** [comment]
I see, good to know. Thx.

**Comment by sebplorenz** [comment]
Done

**Comment by bparees** [comment]
Thanks!

**Pull request merged**
