### PR TITLE
Fixed PostgreSQL addr and port

### LINKED ISSUE #37: Wrong PostgreSQL ports in wfbin/standalone.conf
$POSTGRESQL_PORT_3306_TCP_PORT should be $POSTGRESQL_PORT_5432_TCP_PORT

### PR DESCRIPTION
**Pull request by sebplorenz**
Fixes #37

### CODE REVIEW

**Comment by mfojtik** [comment]
@sebplorenz thanks for fixing this!

**Comment by bparees** [comment]
@sebplorenz @mfojtik 
it really just depends what port you put your DB service on, as to what the right env variable name is here.

**Comment by sebplorenz** [comment]
The image from the openshift/postgresql92 repository uses port 5432. Therefore it works with this image at least. But you're right, the port value should not be part of the parameter name. I didn't figure out where this parameter is set.

**Comment by bparees** [comment]
k8s defines environment variables automatically based on your service definition (name and the port it uses).  So in our particular example template we defined the postgresql service on port 5432, so k8s injects an environment variable named POSTGRESQL_PORT_5432_TCP_PORT and POSTGRESQL_PORT_5432_TCP_ADDR so apps can consume the service.

if you defined a service named postgresql and specified port 3306 then you'd get this instead:
POSTGRESQL_PORT_3306_TCP_PORT
POSTGRESQL_PORT_3306_TCP_PORT

so that's where the variable name is coming from.  hope that clarifies things.  This is kind of an old image and really needs some cleanup, apologies for any headaches it caused you.

**Comment by sebplorenz** [comment]
How would you clean it up? Can you point me to a "cleaner" image? Because I'd like to update the images anyway since I need PostgreSQL 9.4 (for the json support) and also newer PostgreSQL Drivers in the wildfly image. I could contribute that if you like.
Btw. I'm wondering how different versions of a database are handled at all in OpenShift? If there are different versions of PostgreSQL images available and the wildfly image would contain PostgreSQL drivers for the different versions then how does the wildfly container know which driver it should use? (Maybe this is a little bit off topic and I should ask this in the mailing list/irc)?

**Comment by bparees** [comment]
i'd clean it up by fixing up the DB service environment variable handling in standalone.conf.  It should probably take in a single ENV var with a name like DB_SERVICE_NAME and the value would be the name of the k8s service for your DB service.  From there, it could look at the environment, locate the other environment variables injected by k8s (host, port), and populate the datasource definition.  That would be a more generic approach.  There's also really no need for a separatel postgres and mysql datasource, that's a holdover from v2.

even the datasource name could have an env variable piece to it (perhaps that same $DB_SERVICE_NAME value).

the presence of that variable could also serve the role of the *_ENABLED env variable that is processed currently.

The slightly tricky bit is that username and password are not injected by k8s. Those are env variables the app deployer must define for the container, presumably matching them to the values defined in the service itself.  If you use a template to create both the wildfly pod and the db service together, then sharing that value is trivial.

As for different versions... we're only providing a single version of postgres today, but of course it's easy to create additional images for other versions and we'd expect users to do so if they need a different version.  As for which driver to use, i believe there's some compatibility between the drivers, but worst case we allow apps to supply their own standalone.xml entirely, which you could use to explicitly define the datasource with whatever driver you need.

**Pull request merged**
